version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install --target packages -r ./lectures/module_1_class_3/practice/requirements.txt
    finally:
      - echo This always runs even if the update or install command fails
  pre_build:
    commands:
      - echo Zipping deployment package...
      - cd packages
      - zip -r9 ../packages.zip .
      - cd ../lectures/module_1_class_3/practice
      - zip -g ../../../packages.zip my_lambda_handler.py
      - cd ../../../
      - ls
    finally:
      - echo This always runs even if the login command fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - ls
      - aws s3 cp packages.zip s3://lambda-cicd-deployments/
      - aws lambda update-function-code --function-name lambda-with-dependency --s3-bucket lambda-cicd-deployments --s3-key packages.zip

    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`